### ISSUE TITLE
Comments and suggestions

### ISSUE THREAD

**Issue by dmenne** [dcousin3/superb#1]
Hi, Denis,

I read your comment on 

https://stats.stackexchange.com/questions/60767/how-to-display-error-bars-for-cross-over-paired-experiments

and immediately  started reading the documentation. Congratulations, I will make some of your vignettes a recommended reading for my (medical) colleagues.

Some comments: 

- Your github link is difficult to find from the documentation. When you put it into DESCRIPTION, it will be automatically shown on the first page after a website-rebuild. Vice-versa, on the github page, adding the documentation website in About will make the documentation easier recoverable, e.g:.
![2021-04-25 12_12_54-dmenne_breathtestcore_ Core function for reading and processing of 13C breath te](https://user-images.githubusercontent.com/506275/115989654-a4f83a80-a5bf-11eb-95b5-2fafa1d9bae2.png)

- Since medical researchers are always VERY busy and normally not willing to read documentation, some type of flowchart with links in the boxes would be nice ("Did you record data from one subject on multiple occasions") for faster orientation.
- Medical researchers are madly obsessed with what they call "normal ranges", and with some luck to get them to use the recommended term "reference intervals" to avoid "normal ranges of normals with highly skewed distribution". I have seen and reviewed multiple publications where standard errors where used as "normal ranges", leading to surprising 80% outliers in the normals group. This sometimes works with laboratory data, but the obsession carries forward to physiological data such as gastric emptying times where the whole concepts fails.  The more it would be important, if superb could have some additional information on computing referenceIntervals (e.g. with the package with that name), possibly crying loud when 10 points were available with the requirement to compute 95% reference Intervals.

--------------
Some minor typos I noted in the vignettes

**Making Figure 3**: recruted -> recruited

**Four steps**: high density interval (HDI). -> should be highest density interval

**vignette 1**: CM: this method, <called from> the two authors -> <named after>
adjusments -> adjustments

vignette 3: havlved

**Comment by dcousin3** [comment]
Thank you very much for the constructive comments.
1- Added links to About and in DESCRIPTION
2-For the flowchart, a Shiny app is on its way. It should make the steps easier to visualize. Watch for version 0.9.7.5
3-As of the Reference Intervals (RI), many thanks for that! I wrote a new vignette describing how to make plots with these as well as the confidence interval of the tips of that bar.
4- Thanks for the typos, all corrected.
