### ISSUE TITLE
Paired Proportions

### ISSUE THREAD

**Issue by oliviamborges** [dcousin3/superb#3]
Thank you so much for your work in the `superb` package.

In the [Vignette C](https://dcousin3.github.io/superb/articles/VignetteC.html) you explain how it is possible to plot proportions with difference-adjusted confidence intervals.

Do you have any suggestions for plotting proportions from a within-subjects design?

**Comment by dcousin3** [comment]
Hello, In a submitted work, we show that actually, the CA decorrelation technique is valid for Anscombe-Transformed proportions as well. Consequently, you can just add 

    adjustments = list(purpose="difference", decorrelation="CA")

to the ``superbPlot()`` instruction. Here you go!

**Comment by oliviamborges** [comment]
Thank you!
